### ISSUE TITLE
Add a free software license

### ISSUE THREAD

**Issue by alexvong1995** [strazzere/Emacs-Smali#7]
Hello,

Firstly, thanks for creating smali mode for emacs. This is the only one I can
find on the internet.

However, right now it has no license, which means it is not free software and
cannot be shared nor modified freely. 

Please add a free software license, anything from GPLv3+ to CC0 will do.
For reference, see https://www.gnu.org/licenses/license-recommendations.html

**Comment by strazzere** [comment]
Done in https://github.com/strazzere/Emacs-Smali/commit/24d3ac419d0cc4822ea53816bb2f5a115cdee5f3
