### ISSUE TITLE
Some keywords are highlighted in the comments

### ISSUE THREAD

**Issue by dschrempf** [strazzere/Emacs-Smali#8]
Hi, thanks for this small package!

I noticed that some keywords are highlighted in comments (see picture).

![image](https://user-images.githubusercontent.com/5596239/117317331-b5df6080-ae89-11eb-8ad5-75bb2382c827.png)

**Comment by strazzere** [comment]
Appreciate you opening a ticket for this -- however this doesn't really bug me personally. Also, I rarely ever work on files which actually have comments.

If you submit a PR to fix this though, I'm more than happen to test and merge it.

**Comment by strazzere** [comment]
Going to close this due to lack of response -- feel free to reopen with a pull request.
